#!/bin/bash
cd build
./packingtape c ../corpora/english.txt ../output/english.txt.pt
./packingtape d ../output/english.txt.pt ../output/english.txt
sha1sum ../corpora/english.txt
sha1sum ../output/english.txt
